parameters:
#    custom_project.example.class: Custom\ProjectBundle\Example

services:



#    custom_project.example:
#        class: %custom_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
