security:
  #  hide_user_not_found: false  Uncomment this to get more information about login error
    encoders:
       Drufony\CoreBundle\Entity\User: {algorithm: md5, encode_as_base64: false ,iterations: 0 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: DrufonyCoreBundle:User, property: username }

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login: 
                login_path: drufony_login
                check_path: drufony_login_check
                csrf_provider: form.csrf_provider
                use_referer: true
                default_target_path: drufony_home_url
            logout:
                path: drufony_login_logout
                target: drufony_home_url
            remember_me:
                key: "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/[a-z]+/profile, roles: ROLE_USER }
        - { path: ^/[a-z]+/dashboard, roles: ROLE_ADMIN }
        #- { path: ^/[a-z]+/section/add, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
